"""Record real ORCA backend responses for the static web preview.

Runs the actual API in-process (replay mode, no LLM) and saves what it returns
for a scripted set of questions, the map layers, the storm risk layer over 48 h
and the alert fast-forward flow. The static preview replays these; it does not
compute anything itself.

    python scripts/record_demo.py ../web/dist-demo/demo-data.json
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path

os.environ.setdefault("ORCA_NO_DEFAULT_APP", "1")
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from fastapi.testclient import TestClient  # noqa: E402

from orca.api import create_app  # noqa: E402
from orca.llm import NullProvider  # noqa: E402
from orca.services import build_services  # noqa: E402

PLACE = {"lat": 15.40, "lon": 73.70, "location_label": "off Mormugao, Goa"}
SCRIPT = [
    "Where is the nearest Potential Fishing Zone today?",
    "Is it safe to go there tomorrow at 6 AM?",
    "Show me the safest route there tomorrow at 6 am",
    "What are the tide, weather, and sea conditions near my fishing location?",
    "Are there any lightning or cyclone alerts in my area?",
    "Which regions show high chlorophyll concentration and favourable sea surface temperature?",
    "Why has fish productivity declined near Kochi?",
    "Which fishing zones should be avoided due to hazardous marine conditions or geofencing restrictions?",
    "Is it safe to venture into the sea tomorrow morning?",
    "Is it safe to go fishing tomorrow at 6 AM from 15.2,72.8?",
    "कल सुबह गोवा से समुद्र में जाना सुरक्षित है?",
    "நாளை காலை ராமேஸ்வரம் அருகே கடலுக்குச் செல்லலாமா?",
    "రేపు ఉదయం కాకినాడ దగ్గర సముద్రంలోకి వెళ్లవచ్చా?",
    "നാളെ രാവിലെ കൊച്ചിയിൽ കടലിൽ പോകാമോ?",
]
RISK_BBOX = {"lat_min": 8.0, "lat_max": 22.0, "lon_min": 66.0, "lon_max": 77.5}


def main(out: Path) -> None:
    svc = build_services(mode="replay", llm=NullProvider())
    client = TestClient(create_app(svc, alert_interval_s=0, web_dir=Path("/nonexistent")))

    def chat(message: str, session_id: str | None) -> dict:
        r = client.post("/api/chat", json={"message": message, "session_id": session_id, **PLACE})
        r.raise_for_status()
        return r.json()

    conversations: list[dict] = []
    sid = None
    for q in SCRIPT:
        res = chat(q, sid)
        sid = res["session_id"]
        conversations.append({"message": q, "response": res})

    # questions generated by the Zones panel buttons for each zone in the first answer
    extra = []
    for c in conversations[0]["response"]["cards"]["pfz"]["candidates"]:
        lat, lon = c["centroid"]
        extra.append(f"Is it safe at {lat}, {lon} tomorrow at 6 AM?")
        extra.append(f"Show me the safest route to {lat}, {lon} from Goa tomorrow at 6 AM")
    for q in extra:
        conversations.append({"message": q, "response": chat(q, None)})

    health = client.get("/api/health").json()
    clock = datetime.fromisoformat(health["clock"])
    risk_layers = []
    for hours in range(0, 49, 3):
        t = (clock + timedelta(hours=hours)).isoformat()
        layer = client.get("/api/layers/risk", params={**RISK_BBOX, "time": t, "step": 0.3}).json()
        layer["cells"] = [c for c in layer["cells"] if c["level"] != "LOW"]  # LOW is drawn as plain sea
        risk_layers.append({"offset_hours": hours, **layer})

    watch = client.post("/api/alerts/watch", json={"lat": PLACE["lat"], "lon": PLACE["lon"], "label": PLACE["location_label"], "language": "en"}).json()
    advances = [client.post("/api/sim/advance", json={"hours": 6}).json()["alerts"] for _ in range(4)]
    client.post("/api/sim/reset")

    data = {
        "recorded_at": datetime.now().astimezone().isoformat(),
        "place": PLACE,
        "script": SCRIPT,
        "health": health,
        "ports": client.get("/api/ports").json(),
        "geofences": client.get("/api/geofences").json(),
        "rules": client.get("/api/rules").json(),
        "conversations": conversations,
        "risk_layers": risk_layers,
        "alerts": {"watch": watch, "advances": advances},
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(data, ensure_ascii=False, separators=(",", ":")))
    print(f"wrote {out}: {len(conversations)} answers, {len(risk_layers)} risk layers, "
          f"{sum(len(a) for a in advances)} alerts, {out.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main(Path(sys.argv[1] if len(sys.argv) > 1 else "demo-data.json"))
